### ISSUE TITLE
Unable to Connect to dApp with Wallet

### ISSUE THREAD

**Issue by equalogix** [MetaMask/metamask-sdk#260]
**Describe the bug**
There is inconsistent behavior in terms of connecting the dApp with the wallet. The dApp/Wallet get into a state where it becomes impossible to connect. Clicking connect will launch the wallet, but then nothing occurs, it just hangs with no user feedback of any kind.

**To Reproduce**
Steps to reproduce the behaviour:
It appears that the issue is being caused by stale or potentially stale data being stored in `localStorage`. If the user closes a tab or for some reason navigates away from the dApp in the browser without disconnecting first then when the user returns they are not connected but the data from the previous session remains in `localStorage`. Then when the user clicks connect, the dApp will be unable to connect. If one clears the `localStorage` in dev-tools and then tries to connect in generally works.

To reproduce simply connect to the dApp then close the browser tab, reopen a new browser tab, go to the dApp again and try to re-connect.

In the code shown below, I set it up such that the `connecting...` message which appear after click `connect`  is a button that disconnects the user and clears the storage. So once you are unable to connect if you click the `connecting...` button and then click `connect` you should connect successfully.

**Expected behaviour**
When a user clicks connect, the user should be able to connect their wallet. If for some reason the connection cannot occur, there needs to be some feedback such that the dApp can clear its cache and try again.

There is no documented way of reconnecting to the dApp after a page refresh (ie: persisting the session). Clearly since data is stored in `localStorage` there must be away to reconnect to that session with minimal user interaction.

**Screenshots**
NA

** Provide environment information**
- Platform Web desktop and mobile
- MetaMask SDK Version: latest
- MetaMask Mobile Version: v7.3.1 [Android]
- Browser (if relevant):

**Additional context**
Here is the code:
File: MMSDKConnector.js
```js
import React, {
  createContext,
  useContext,
  useEffect,
  useState,
  useRef,
} from "react";
import { useSDK } from '@metamask/sdk-react';
import { Web3Provider, Provider } from "zksync-web3";

export const WalletContext = createContext(null);

export const WalletClient = ({children}) => {
    const [account, setAccount] = useState();
    const [signer, setSigner] = useState();
    const zkProviderRef = useRef();
    const {sdk, connected, connecting, provider, chainId} = useSDK();

    useEffect(() => {
      if(provider) {
        zkProviderRef.current = new Web3Provider(provider);
      }
    },[provider])

    const handleConnect = () => {
      console.log("connectizing sdk", sdk)
      sdk?.connect()
        .then( accts => {
          console.log("connected sdk", accts)
          setAccount(accts?.[0]);
        })
        .catch(err => {
          console.warn(`failed to connect..`, err);
        })
    }

    const handleDisconnect = () => {
      console.log("disconnectionizing sdk")
      sdk?.terminate();
      setAccount();
      setSigner();
      window.localStorage.clear();
      console.log("disconnectedized");
    }

    return (
      <WalletContext.Provider
        value={{
          account, setAccount,
          chainId,
          // providerRef,
          zkProviderRef,
          signer, setSigner,
          handleConnect, handleDisconnect, connected, connecting
        }}
      >
        {children}
      </WalletContext.Provider>
    )
  }

export const useAccount = () => {
  const { account, setAccount } = useContext(WalletContext); 
  return { account, setAccount }
}

export const useSigner = () => {
  const { signer, setSigner } = useContext(WalletContext); 
  return { signer, setSigner }
}

export const useChainId = () => {
  const { chainId, setChainId } = useContext(WalletContext); 
  return { chainId, setChainId }
}

export const useZkProvider = () => {
  const { zkProviderRef } = useContext(WalletContext); 
  const { current: zkProvider } = zkProviderRef;
  return { zkProvider }
}

export const useConnector = () => {
  const { 
    handleConnect, 
    handleDisconnect,
    connected,
    connecting
  } = useContext(WalletContext);
  return { handleConnect,handleDisconnect, connected, connecting }
}  

const styles = {
  button: {
    color: "#000",
    background: "#bbb",
    padding: 8,
    width: 120
  },
  widget: {
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    flexDirection: "column",
    width: "300",
    padding: 12,
    background: "#444",
    color: "#DDD",
    border: "solid #ddd 1px",
    borderRadius: 4
  }
}

export const MMConnector = () => {
  const { account } = useAccount();
  const { zkProvider } = useZkProvider();
  const { setSigner } = useSigner();
  const { handleConnect, handleDisconnect, connected, connecting } = useConnector();
  const chainIdInt = 280;

  useEffect(()=>{ 
    if(account && zkProvider) {
      setSigner(zkProvider.getSigner())
    }
  }, [account, zkProvider]);

  return (
    <>
    { connected ? (
      <>
      <button 
        style={styles.button}
        onClick={() => {handleDisconnect()}}
      >
        Disconnect
      </button>
      </>
    ) : ( connecting ? (
      <button 
        style={styles.button}
        onClick={() => {handleDisconnect()}}
      >
        Connecting...
      </button>
    ) : (
      <button 
        onClick={handleConnect}
        style={styles.button}
      >
        Connect
      </button>
    ))}
    </>
  )
}

export const WalletWidget = () => {
  const { account } = useAccount();
  const { chainId } = useChainId();
  
  return (
    <div style={styles.widget}>
      <h3>Connect Wallet</h3>
        <>
        { account && (
          <>
            <div>Connected with: MetaMaskSDK</div>
            <div>On Chain: {parseInt(chainId)} ({chainId})</div>
          </>
        )}
        <MMConnector />
        </>

    </div>
  )
}
```

File: App.js
```js
import React, { useState, useRef } from 'react';
import { WalletClient, WalletWidget } from "./MMSDKConnector";
import { MetaMaskProvider } from '@metamask/sdk-react';
import { useSigner } from "./MMSDKConnector";

export const SignMessageButton = (props) => {
  const {message} = props;
  const {signer} = useSigner(); 
  const [signedMsg, setSignedMsg] = useState();
  const timeoutRef = useRef();

  const signMessage = () => {
    if(!signer) return
    signer.signMessage(message)
      .then( x => { 
        console.log("signed msg:", x)
        setSignedMsg(x)
        timeoutRef.current = setTimeout( () => {setSignedMsg()}, 3000)
      })
      .catch( err => { console.error(err)})
  }

  return (
    <>
    {signer && <button onClick={signMessage}>Sign Message</button>}
    {signedMsg && <div style={{width:300, overflow:"clip"}}>{signedMsg}</div>}
    </>
  )
}


export default function App() {
  return (
    <MetaMaskProvider
      debug 
      sdkOptions={{
        logging:{
            developerMode: true,
          },
          checkInstallationImmediately: false, // This will automatically connect to MetaMask on page load
          checkInstallationOnAllCalls: false,
          dappMetadata: {
            name: "Demo React App",
            url: window.location.host,
          }
      }}
    >
    <WalletClient>
      <div style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        margin: 16,
        padding: 16,
        background: "#333",
        borderRadius: 16
      }}>
        <WalletWidget/>
        <div style={{
          background: "#ccc",
          padding:16,
          margin: 16,
          borderRadius: 16,
          textAlign: "center"
        }}>
        <SignMessageButton message="Test Message!" />
        </div>
      </div>
    </WalletClient>
    </MetaMaskProvider>
  )
}

**Comment by andreahaku** [comment]
Hi @equalogix, to confirm: when using iOS MM mobile app it works, while on Android it doesn't.

Also, sorry for the slow reply but the team is off this week. We'll be back in full force from Monday.

**Comment by christopherferreira9** [comment]
Hi @equalogix , you can also terminate and remove the connection from the dapp side by calling  the terminate method like:
```  
const terminate = () => {
    sdk?.terminate();
}
```

where sdk is the metamask-sdk instance

**Comment by andreahaku** [comment]
@equalogix we have just updated the code of the socket.io server to be more performing and reliable. As one of the possible issue may have been the socket.io code not being able to handle traffic peaks properly, can you please try checking again now and tell us if you see some improvements or if you still have the same issues? Thanks

**Comment by christopherferreira9** [comment]
Hi @equalogix ! I've also bumped into this issue but usually when I do I'm purposely messing with the connection. If you're able can you share a video getting into that state or being already at it?

**Comment by christopherferreira9** [comment]
Thank you for the video @equalogix ! Do you see any particular logs on de dapp side when you tap connect? Here are some questions that can help us debug the issue:
- Are you using any sort of DNS filtering on your network?
- Are you using any VPN while trying to connect?

Also, while we look into this, can you add another button to the dapp that performs `sdk.terminate()` and try the following flow:
1. Clean connections on the wallet
2. Kill wallet 
3. Open dapp and tap terminate
4. Kill dapp
5. Open Wallet and unlock
6. Open dapp
7. Tap connect

Thank you for your patience and evidence!

**Comment by christopherferreira9** [comment]
It is indeed! We'll try our best to look into this using your dapp and multiple setups (different phones and other environments).

**Comment by christopherferreira9** [comment]
Hi @equalogix ! Can you confirm that the MetaMask Wallet version is still 7.3.1?

**Comment by christopherferreira9** [comment]
Hi @equalogix ! We've just released a new version for the `@metamask/sdk` package. Can you please try with that one?

**Comment by shin101004** [comment]
I experienced same problem.

here is my log

```shell
Message ignored because invalid key exchange status BOLveS0s80bcKgpkEeheb34Y5abmXHj5vBQNoFOQyCFJUk0c2pBA4ZvasIw5N/Xi29W4usyjfISx4skT05dNARKZHxwwgWjdBl6kk1lcCRZPlWC//j/AUP88sagZwerkPxQzn3/OaUoCidx/Nsya6uw= 
```

it happens especially on android.

if metamask run on background, my connection request is ignored. it return nothing.

also i reported another issue before.

sdk team closed my issue, it still exist.

here is link https://github.com/MetaMask/metamask-sdk/issues/127

**Comment by christopherferreira9** [comment]
@shin101004 please re-open the original ticket if it wasn't solved for you.

**Comment by christopherferreira9** [comment]
hi @equalogix !
I've also been bumping into a similar behaviour when multiple requests are not processed as they should. They seem to get queued until a connection is able to resume. It happens often on slower devices, there's a clear difference between my Samsung S20FE and Pixel 7a where the samsung get's stuck much more.
We plan to improve the overall behaviour of the SDK on the wallet side before releasing V1 and by then we should be able to turn this into a more solid experience.

**Comment by andreahaku** [comment]
@equalogix can you please add `useDeeplink: true` to your MM SDK initialisation (in the `sdkOptions`)?
I suspect that the issue is with the universal links and by using deeplinks instead it should work if that's the cause.

```
- `useDeeplink`: boolean (default: false) - If true, the SDK will use deeplinks to connect with MetaMask Mobile. If false, the SDK will use universal links to connect with MetaMask Mobile.
```

**Comment by andreahaku** [comment]
@equalogix did you try on different Android devices? Did you try uninstalling and reinstalling the Android MM mobile app from the Google store? Make sure you have your SRP to restore the accounts if it's not a test installation ;) Thanks

**Comment by christopherferreira9** [comment]
@equalogix we have a potential fix that will be part of the MetaMask Wallet v7.9 that should be released in the second week of October. Let us know how the test on the other device goes.

**Comment by christopherferreira9** [comment]
@equalogix We've submitted the`v7.9` to the stores so you should have an update soon to try this on.

**Comment by christopherferreira9** [comment]
Hi @equalogix ! Did you manage to check this with version 7.9 of the Wallet?

**Comment by christopherferreira9** [comment]
We are closing this issue due to inactivity.
